version: "3"
services:
  nodejs:
    build: nodejs
    command: bash -c "cd /webapp/lib/configs && cp server.js.dist server.js && npm start"
    volumes:
      - ../server:/webapp
    ports:
      - 3000:3333
  mongo:
    image: mongo:3.4.10
    command: mongod --dbpath /data/db --port 27017
    volumes:
      - ../server:/webapp
    ports:
      - 27017:27017

  elastic:
    build: elastic
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ../server:/webapp

  swift:
    image: morrisjobke/docker-swift-onlyone
    ports:
      - 8080:8080
    volumes:
      - ../server:/webapp