version: "3"
services:
  mongo:
    image: mongo:3.4.10
    command: mongod --dbpath /data/db --port 27017
    volumes:
      - ../server:/webapp
    ports:
      - 37017:27017
  elastic:
    build: elastic
    ports:
      - 29200:9200
      - 29300:9300
    volumes:
      - ../server:/webapp
  swift:
    image: morrisjobke/docker-swift-onlyone
    ports:
      - 28080:8080
    volumes:
      - ../server:/webapp
  nodejs:
    build: nodejs
    command: bash -c "cd /webapp && npm install && if [ ! -f lib/configs/server.js ]; then cp lib/configs/server.js.dist lib/configs/server.js; fi && npm start"
    volumes:
      - ../server:/webapp
    ports:
      - 23000:3333
    depends_on:
      - mongo
      - elastic
      - swift
      
